[tool.black]
line-length = 88  # número máximo de caracteres por linha
target-version = ['py311']  # versão alvo do Python
skip-string-normalization = true  # mantém aspas simples ou duplas como no original

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F"]          # E: pycodestyle, F: pyflakes
ignore = ["E501"]            # Exemplo: ignorar linha longa
exclude = ["*.env"]


[tool.ruff.format]
docstring-code-format = true  # formata código dentro de docstrings
